### ISSUE TITLE
Nothing works.

### ISSUE THREAD

**Issue by slimcdk** [wellsjo/cryptowatch-api#5]
None of the listed methods can be used.

Some of what I've tried:
```
const cryptowatch = require('cryptowatch-api');

app.route('/exchanges')
    .get((req, res) => {
        res.json(cryptowatch.exchanges());
});
```

The error I get is;
`
TypeError: cryptowatch.prices is not a function`

Express is properly configured.

**Comment by wellsjo** [comment]
@slimcdk Two problems.

1. You need to instantiate an instance of `cryptowatch` since it is a class.
2. `exchanges` returns a promise, so you can't return data from it directly.

The following should work:
```javascript
const cw = require('cryptowatch-api');
const cryptowatch = new cw();
app.route('/exchanges')
    .get((req, res) => {
        cryptowatch.exchanges().then(exchanges => {
            res.json(exchanges);
        })
});
```
